# Generated by Django 4.2.21 on 2025-06-03 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.PositiveIntegerField(default=0)),
                ('self_control', models.PositiveIntegerField(default=0)),
                ('social', models.PositiveIntegerField(default=0)),
                ('well_being', models.PositiveIntegerField(default=0)),
                ('economy', models.PositiveIntegerField(default=0)),
                ('knowledge', models.PositiveIntegerField(default=0)),
                ('physical', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('violet', 'Emotion（感情）'), ('indigo', 'Self-control（自己制御）'), ('blue', 'Social（社会的関係）'), ('green', 'Well-being（ウェルビーイング）'), ('yellow', 'Economy（経済）'), ('orange', 'Knowledge（知識）'), ('red', 'Physical（身体）')], max_length=20)),
                ('description', models.TextField()),
                ('exp', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
